# Generated by Django 5.2.5 on 2025-08-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(max_length=40)),
                ('product_image', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('product_name', 'market')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=255)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
        ),
    ]
