# Generated by Django 5.2.5 on 2025-09-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='market',
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
    ]
