services:
  migros-scraper:
    build:
      context: 'C:\Users\your_user\Desktop\projects\PriceTrack'
      dockerfile: Dockerfile.migros
    container_name: migros_scraper
    environment:
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: root
      RMQ_PASSWORD: 'root'
      MIGROS_CATEGORIES_URL: https://www.migros.com.tr/rest/categories
      MIGROS_API_URL: https://www.migros.com.tr/rest/search/screens/
    networks:
      - main_net

networks:
  main_net:
    external: true