services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_LOAD_DEFINITIONS: "/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - C:\path\to\pricetrack_rmq:/var/lib/rabbitmq 
      - C:\path\to\pricetrack\setup\rmq-definitions.json:/etc/rabbitmq/definitions.json:ro
      - C:\path\to\pricetrack\setup\rmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - main_net
      
networks:
  main_net:
    external: true